### ISSUE TITLE
Transparent xposed icon? 

### ISSUE THREAD

**Issue by terrorist96** [DVDAndroid/XposedInstaller#101]
Just noticed this with the latest version
![img_20160718_013430](https://cloud.githubusercontent.com/assets/12802056/16906581/ec7cd5fa-4c87-11e6-9cb1-d1112c827c79.jpg)

**Comment by DVDAndroid** [comment]
Frequency? Which color you have chosen in the app? Is the option "colorate notification icon" enabled?

**Comment by terrorist96** [comment]
All the time, whenever a module updates or new module downloaded. I have a blue color chosen, but "colorate notification icon" is off

**Comment by DVDAndroid** [comment]
The icon was black
