### ISSUE TITLE
Xposed Installer crashes after I click on any module

### ISSUE THREAD

**Issue by akeshma** [DVDAndroid/XposedInstaller#111]
Hi
using 86.2 systemless xposed and material installer 

Xposed Installer crashes after I click on any module
[logcat1.txt](https://github.com/DVDAndroid/XposedInstaller/files/381832/logcat1.txt)
 to download it !!!

any help

I have just installed the 86.2 systemless xposed with fresh installtion (Huawei P9)

**Comment by DVDAndroid** [comment]
Log is not useful... Try to clear app's data and try again

**Comment by DVDAndroid** [comment]
Uninstall my version of the installer and [use this](http://forum.xda-developers.com/attachment.php?attachmentid=3788578&d=1466364724)

**Comment by DVDAndroid** [comment]
Can you try to reproduce bug and get another logcat, please?

Please [try this apk](http://www.filedropper.com/xposedinstallerbydvdandroid-debug_4)

**Comment by akeshma** [comment]
Hi. Any new update to solve this issue!?
Thanks for your efforts

**Comment by DVDAndroid** [comment]
@akeshma Please [try this apk](http://www.filedropper.com/xposedinstallerbydvdandroid-debug_4)

It might seem like a silly question, but what is your language?

**Comment by akeshma** [comment]
I'm Arabic but using English in my daily work
Logcat:
https://www.dropbox.com/s/csbary99tdh0hdi/logcat_and_device_info.zip?dl=0

**Comment by DVDAndroid** [comment]
Have you tried linked apk?
Does it crashes? From log I cannot understand if it crash or not

**Comment by akeshma** [comment]
With using this file it works now 

Thanks a lot for your help

**Comment by DVDAndroid** [comment]
Ok, nice

**Comment by DVDAndroid** [comment]
If you have other problems, please feel free to comment here

**Comment by akeshma** [comment]
What is the changes done to solve this issue .

**Comment by DVDAndroid** [comment]
I used a database to store bookmarks.
I read that the library that I used to create the bookmarks, crashed if it reads an arabic character. (I'm not sure, however)

Have you cleaned app's data when installing the apk that I linked you?

**Comment by akeshma** [comment]
No I have not clean any thing

**Comment by DVDAndroid** [comment]
Ok, perfect
