### ISSUE TITLE
App crashes when choosing item in Download

### ISSUE THREAD

**Issue by Qu3ntin0** [DVDAndroid/XposedInstaller#12]
Whenever I try to choose a module in DownloadDetailsActivity, the app crashes. Here's the logcat:

01-05 22:03:47.824 I/ActivityManager(  821): START u0 {dat=package: cmp=de.robv.android.xposed.installer/.DownloadDetailsActivity (has extras)} from uid 10007 on display 0

01-05 22:03:47.834 D/PMS     (  821): acquireWL(16ef58a0): PARTIAL_WAKE_LOCK  ActivityManager-Launch 0x1 821 1000 null

01-05 22:03:47.854 D/HtcSystemUPManager(  821): HtcSystemUPolicy [canLog (default)] category: launch, enable: true

01-05 22:03:47.864 E/SQLiteLog(24759): (1) no such column: size

01-05 22:03:47.874 W/ActivityManager(  821):   Force finishing activity de.robv.android.xposed.installer/.DownloadDetailsActivity

01-05 22:03:47.874 E/AndroidRuntime(24759): FATAL EXCEPTION: main

01-05 22:03:47.874 E/AndroidRuntime(24759): Process: de.robv.android.xposed.installer, PID: 24759

01-05 22:03:47.874 E/AndroidRuntime(24759): java.lang.RuntimeException: Unable to start activity ComponentInfo{de.robv.android.xposed.installer/de.robv.android.xposed.installer.DownloadDetailsActivity}: android.database.sqlite.SQLiteException: no such column: size (code 1): , while compiling: SELECT name, code, download_link, md5sum, size, changelog, changelog_is_html, reltype, uploaded FROM module_versions WHERE module_id = ?

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.app.ActivityThread.access$800(ActivityThread.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.os.Handler.dispatchMessage(Handler.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.os.Looper.loop(Looper.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.app.ActivityThread.main(ActivityThread.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at java.lang.reflect.Method.invoke(Native Method)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at java.lang.reflect.Method.invoke(Method.java:372)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)

01-05 22:03:47.874 E/AndroidRuntime(24759): Caused by: android.database.sqlite.SQLiteException: no such column: size (code 1): , while compiling: SELECT name, code, download_link, md5sum, size, changelog, changelog_is_html, reltype, uploaded FROM module_versions WHERE module_id = ?

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at de.robv.android.xposed.installer.repo.RepoDb.getModuleByPackageName(RepoDb.java:290)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at de.robv.android.xposed.installer.util.RepoLoader.getModule(RepoLoader.java:157)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at de.robv.android.xposed.installer.DownloadDetailsActivity.onCreate(DownloadDetailsActivity.java:53)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.app.Activity.performCreate(Activity.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)

01-05 22:03:47.874 E/AndroidRuntime(24759):     ... 12 more

**Comment by DVDAndroid** [comment]
Try to clear cache. If doesn't work, clear app data

**Comment by DVDAndroid** [comment]
@Qu3ntin0 is the bug fixed?

**Comment by Qu3ntin0** [comment]
@DVDAndroid yep I think the problem was that I installed it over the original one.
