### ISSUE TITLE
Not  Working in SM-N9005 Note 3

### ISSUE THREAD

**Issue by panchalvivek007** [DVDAndroid/XposedInstaller#135]
Dear  Xposed

its  not  Working in Samsung Galaxy Note 3 SM-N9005  sdk 21
lollipop  armv7   I try  Install  zip  But  My  Phone gets bootloop

Please  help  out
Give  Me Linkk For My Phone

**Comment by DVDAndroid** [comment]
It's not a Xposed Installer issue
Ask on XDA: [this thread](http://forum.xda-developers.com/xposed/unofficial-xposed-samsung-lollipop-t3113463)

**Comment by DVDAndroid** [comment]
Android version?
