### ISSUE TITLE
Long module version names misshape card layout

### ISSUE THREAD

**Issue by wasdennnoch** [DVDAndroid/XposedInstaller#137]
For example, the automated builds of Android N-ify have a very long version name. This revealed a little layout issue of the module card:

![screenshot_20160918-200414](https://cloud.githubusercontent.com/assets/10065021/18617894/91979064-7ddb-11e6-857b-b810d5fb9365.png)

The version text takes up the full width so the app name needs several lines. It also is too small to be visible.
Fixing methods: Set the max lines of the app name to 2/3, give the version TextView a max width. Also the LinearLayout they are in should have an orientation attribute for better readability ;)

And yes, the version name really should be shorter, but the installer should also be compatible :P
- Material Xposed Installer version: `14/09/2016`

**Comment by DVDAndroid** [comment]
Can you provide me the apk? I downloaded it from Jenkins but the bug is not visible.
Should I build it from Android studio manually?

![screenshot_20160918-202833 2](https://cloud.githubusercontent.com/assets/6277172/18618061/9e869c90-7dde-11e6-8428-7aaaaa52f465.png)

**Comment by DVDAndroid** [comment]
(I can always create an empty module with long version name)

**Comment by wasdennnoch** [comment]
The experimental builds have the long name: https://ci.paphonb.xyz/jenkins/job/AndroidN-ify_experimental/

**Comment by DVDAndroid** [comment]
Now the textview of version name is animated if too long and it has a max width of 100dp

**Comment by rovo89** [comment]
To me, the animation gives the screen a nervous touch. Such a long version name isn't a good idea anyway. So I think it's better just to limit the width and ellipsize in the middle of the text. That way, the beginning and the end are still visible.
