### ISSUE TITLE
[Enhancement] Ability to ignore/hide specific module updates

### ISSUE THREAD

**Issue by WildS0ft** [DVDAndroid/XposedInstaller#146]
I would like to request a feature to be able to ignore a specific module update or all future updates to a module.

To clarify; I want to be able to hide the notification that there's a new version of a certain module for all future updates to that module. But I'd also like the option to just ignore specific versions of a module, so I'd get notified of the next update to it.

**Comment by DVDAndroid** [comment]
An option to ignore/hide update is available in settings in the sperimental category.

It's not possible to hide specific version of the module, however.

**Comment by WildS0ft** [comment]
I can't seem to be able to find that setting. The only one I can see is "`Enable Heads-Up notification`" and "`Enable module update notification`". But that would turn it off for every module.

Ignoring specific versions would also be neat =)

**Comment by DVDAndroid** [comment]
![screenshot_20161027-124336](https://cloud.githubusercontent.com/assets/6277172/19769629/772ed1de-9c5c-11e6-82ed-3d603328fbc1.png)

Ignore updates for a module is a bit unstable; I'm not planning to extend this feature
