### ISSUE TITLE
Can't open Xposed on MIUI8

### ISSUE THREAD

**Issue by PepbookPvP** [DVDAndroid/XposedInstaller#161]
###### Include the following:
 - Xposed Version: `85` 
 - [ ] Xposed Systemless
 - Device OS version: `5.1.1`
 - Device Manufacturer: `Mi(Xiaomi)`
 - Device Name: `2014816(wt86047,Redmi 2A Pro)`
 - Material Xposed Installer version: `14/09/2016`
 
###### Reproduction Steps

1.Download the pack, for sure
2.Install, no problems
3.Try to open, but failed.

###### Expected Result
The MIUI Version is a bit old(6.12.4), and it's not the official version (downloaded from xiaomi.eu). it was cut by myself and i think there's still a bug in the uncut version.
Oppps, i didn't tell that I tried official version, and it works,  but....The framework doesn't work.
###### Actual Result
Hmm...Nope:( Maybe I should update the version :P

**Comment by DVDAndroid** [comment]
You should try [latest version](https://forum.xda-developers.com/devdb/project/dl/?id=21776&task=get)

If it doesn't work you should try the [test version](https://forum.xda-developers.com/devdb/project/dl/?id=21795&task=get)

**Comment by DVDAndroid** [comment]
Which official version have you installed (versione name)?

**Comment by DVDAndroid** [comment]
@PepbookPvp up

**Comment by DVDAndroid** [comment]
Issue closed for lack of info

**Comment by PepbookPvP** [comment]
Well...I updated my system and xp version and it works!
Sorry for that, I'm busying with my school, so I don't have much time checking my github.
Thanks:)
