### ISSUE TITLE
force English language is not always working

### ISSUE THREAD

**Issue by craftwar** [DVDAndroid/XposedInstaller#162]
###### Include the following:
 - Xposed Version: `87` 
 - Xposed Official
 - Device OS version: `6.0.1`
 - Device Manufacturer: `ASUS`
 - Device Name: `ZOOED`
 - Material Xposed Installer version: `26/11/2016`
 
###### Reproduction Steps

1.  open Xposed installer (it happens randomly)

###### Expected Result
Display in English

###### Actual Result
Display in phone locale (Traditional Chinese)

If I close and reopen, it works normally. (display in English)

**Comment by DVDAndroid** [comment]
Have you removed the app from recent screen after enabling the force language option?

**Comment by craftwar** [comment]
Yes, that's why i say random bug.
just notify that, not a serious bug to me.
