### ISSUE TITLE
Downloading update fails

### ISSUE THREAD

**Issue by terrorist96** [DVDAndroid/XposedInstaller#165]
###### Include the following:
 - Xposed Version: `87` 
 - [x] Xposed Systemless
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6p`
 - Material Xposed Installer version: `29/04/2017`
 
###### Reproduction Steps

1. Go to Framework tab
2. Tap update button at bottom

###### Expected Result
For update to download

###### Actual Result
Downloads for a little bit but stops before finishing

**Comment by terrorist96** [comment]
@DVDAndroid so do I have to manually download the apk again (in order to receive this new fix)?

**Comment by DVDAndroid** [comment]
Yes
