### ISSUE TITLE
Module enabling issue

### ISSUE THREAD

**Issue by ghost** [DVDAndroid/XposedInstaller#178]
###### Include the following:
 - Xposed Version: `88` 
 - [ ] Xposed Systemless
 - Device OS version: 7.1.2
 - Device Manufacturer: `ZTE`
 - Device Name: `Axon 7
 - Material Xposed Installer version: `?`
 
###### Reproduction Steps

1. Install Modules
2. Check and Uncheck a few over various reboots. End with the all checked
3. Test to see if they work

###### Expected Result
That if all the modules are checked they would work

###### Actual Result
Modules aren't enabled. Going to apps that require xposed shows. Xposed module is not enabled. uncheck and recheck apps. Fix is to uninstall and reinstall xposed installer.

**Comment by DVDAndroid** [comment]
Why is Xposed installer version set to `?` ?

If you have upgraded Xposed installer from version 3.0.1 to 3.1.2 test it's normal behaviour

**Comment by ghost** [comment]
It was version 88 I believe 
My issue originally came from uninstaller magisk xposed from the installer APP. Maybe doing that again will recreate the situation.

**Comment by ghost** [comment]
I can not produce this issue any more
- titanium backup to install the modules
- enable in xposed installer works now with the current version
I believe this was an issue with the version I was using before
