### ISSUE TITLE
No Installer Update Notifications... 

### ISSUE THREAD

**Issue by Ibuprophen** [DVDAndroid/XposedInstaller#181]
- Xposed Version: `88` 
 - [ ] Xposed Systemless
 - Device OS version: `6.0.1` (CM13) 
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S5` (kltevzw)
 - Material Xposed Installer version: `18/10/2017`

  i didn't receive any notifications nor, when I opened the Installer, it didn't reflect any updates for the Installer app. 

I did double check the settings and confirmed that the notifications are still selected to receive them. 

I did download the update via the DevDB Downloads Tab here and it installed without a problem.

The Installer and Modules were working fine prior to and after the update. 

Just in case you would like, I had attached a copy of the Installer Log File. 

I just wanted to bring this to your attention. 

Thank you very much! :-) 

[xposed_error_20171018_110805.log](https://github.com/DVDAndroid/XposedInstaller/files/1395141/xposed_error_20171018_110805.log)

**Comment by DVDAndroid** [comment]
Work as expected. No bugs

**Comment by Ibuprophen** [comment]
I wasn't stating that the installer wasn't working itself but, i am not getting the notifications. 

Oh well... As long as I've got an alternative to this then I won't bother you any longer about it. 

Thank you very much for your time! :-)

**Comment by Bluscream** [comment]
@dvdandroid keep your shit together

**Comment by DVDAndroid** [comment]
@Bluscream are you ok?
