### ISSUE TITLE
Please merge "requires" logic

### ISSUE THREAD

**Issue by rovo89** [DVDAndroid/XposedInstaller#184]
Hi, I have added something to the official installer to prevent situations where people are still using an old installer and wonder why the framework doesn't work properly. Basically, `xposed.prop` can now contain lines like `requires:fbe_aware=1`, which signals to the installer that it needs to support the `fbe_aware` feature. The installer has a list of features it supports, and as long as all required features are supported by the installer, all is fine. Otherwise, it won't allow installing the ZIP and will show a "known issue" warning if the user managed to install the ZIP anyway. This will ask the user to update.

I know that you have your own update reminders, but please merge this anyway:
https://github.com/rovo89/XposedInstaller/commit/ffa1e3afabffeeeda3861a52d79d483462d47e82
https://github.com/rovo89/XposedInstaller/commit/b3afd0b87c6afab068c42f7b17d69ae4d977f820
https://github.com/rovo89/XposedInstaller/commit/ff695eba7f5347700bec5f7dd0961c3e59d789ad
https://github.com/rovo89/XposedInstaller/commit/8a50348713c3cd5a25cd0db5aedc939308a6524b
https://github.com/rovo89/XposedInstaller/commit/4b87be3147a6a387c39ccde81514db7becb74c57
https://github.com/rovo89/XposedInstaller/commit/5e9d4346840e7a4f0b5f9a2e8293743c002097dc

Feel free to adjust it to your own needs. The only thing that would be required (by a new check in XposedBridge) is that there is a resource string called `installer_needs_update`. Otherwise, the framework would show a Toast message.

**Comment by rovo89** [comment]
Just added another commit to take the app name from the existing string resource: https://github.com/rovo89/XposedInstaller/commit/5e9d4346840e7a4f0b5f9a2e8293743c002097dc

**Comment by DVDAndroid** [comment]
Just pushed :+1:

**Comment by rovo89** [comment]
Cool, thanks!
