### ISSUE TITLE
No Notifications With Your Latest XPosed Installer Release... 

### ISSUE THREAD

**Issue by Ibuprophen** [DVDAndroid/XposedInstaller#189]
I've been noticing some issues @DVDAndroid that only happens with your last 2 Installer releases. 

After module installs and updates, i don't receive any popup notifications and even confirmed that the settings were still kept to receive them but, I never do. 

Also, after updating modules and rebooting, though their still selected in the module list, they are not actually active and I'm forced to clear the check box for the updated module, reboot, select to activate the module again and reboot again and all is well again. 

So I had tried a little test to see if it was still present for Rovo89's latest installer (i may have gone abroad and beyond with the following)... 

I first cleared all the selection boxes to deactivate the modules then reboot the device. I then force stop the Installer, clear the data/cache and then i uninstall the XPosed Installer app.

I then install @rovo89 latest Installer, open it and select all the modules to activate them and then rebooted the device and all was working. 

I then reinstalled one of the modules and am now receiving the notifications. 

This led me to believe that it's the Material Design Installer since Rovo89's installer provides the notifications. 

I just wanted to bring this to your attention and also provided a screenshot of the notification that your installer wasn't providing. 

Thank you very much for your time and understanding! 

[active](https://user-images.githubusercontent.com/18060271/32518785-a826f8da-c3d8-11e7-8850-71f1783b69fb.jpg)

[notification](https://user-images.githubusercontent.com/18060271/32518822-befc76de-c3d8-11e7-9890-3eaa2998ec96.jpg)

**Comment by DVDAndroid** [comment]
Could you try this [apk](https://github.com/DVDAndroid/XposedInstaller/files/1454327/XposedInstaller_by_dvdandroid_31_10_17.zip)? (replace .zip with .apk)

**Comment by Ibuprophen** [comment]
Thank you @DVDAndroid... 

I'll get back to you soon with the results.

**Comment by Ibuprophen** [comment]
PERFECT!!! 

Thank you SOOO MUCH @DVDAndroid. 

![eddie-murphy-o tay](https://user-images.githubusercontent.com/18060271/32563536-8b58b7fa-c47f-11e7-8969-ad463c521d4b.jpg)

**Comment by Ibuprophen** [comment]
I only reopened this issue @DVDAndroid because the one that you had me try did work as well as others on the XDA forum thread had also been experiencing the same issue too.

**Comment by rmenessec** [comment]
This issue affects me. I never receive notifications of new updates being available to install from the Xposed installer, and I only seem to receive prompts to enable / reboot if I install a module directly from the Xposed installer. If I install an Xposed app from another source, like Greenify via Google Play or anything from a local APK install - like from a file manager app - I don't seem to get prompts to enable / reboot.

I don't recall ever being promoted to reboot after an Xposed module **update** , either; only for new installs.

Offtopic for a moment: is the bookmark functionality ever going to do anything? I mean, I can bookmark and un-bookmark, but there's no "wishlist," and there's no bookmarked "status" to see or sort by...

Thanks!

**Comment by DVDAndroid** [comment]
I'll push an update soon
