### ISSUE TITLE
Quick Question Regarding Your XDA Downloads... 

### ISSUE THREAD

**Issue by Ibuprophen** [DVDAndroid/XposedInstaller#195]
Hello Again @DVDAndroid! :-) 

There's a handful of members that are reporting issues with obtaining your apk downloads via your XDA Thread Downloads area. 

If it were isolated to one or two then it wouldn't be a big enough deal for me to report it here but, it seems as though enough members reported an issue on your thread and other locations as well. 

Approximately 90% of the members have no problem but, I believe, that some regions are having an issue with obtaining any of the apk files. 

What I'm asking is if you could please provide an alternative method via Github (or elsewhere like your AFH Account) for those who are having this issue so they can obtain the apk files. 

Thank you very much for your time, patience, support and understanding with this! :-) 

~Ibuprophen 
XDA - RC

**Comment by DVDAndroid** [comment]
Hi! It's been a while since I updated the thread on XDA. I'll fix soon and I'll provide a mirror.

**Comment by Ibuprophen** [comment]
Thank you very much @DVDAndroid! :+1: 

There was a recent member who was really trying to obtain the last apk release and i had provided a link to my AFH account where i have an archive of your apk's that are all untouched/unmodified ONLY as an alternative.

I assure you that i had specified that members always obtain downloads from the source links provided by the developer and that my link is only an alternative (an "if all else fails" option) until everyone is able to obtain the developers downloads. 

If you want me to remove the link, i will do so but, i planned to do so if/when you were able to straighten the downloads issue out.

Thank you very much for your prompt response! :-) 


~Ibuprophen
XDA-RC

**Comment by DVDAndroid** [comment]
No problems. You can leave that link 👍
