### ISSUE TITLE
not support android 8.1.0

### ISSUE THREAD

**Issue by hhhaiai** [DVDAndroid/XposedInstaller#196]
###### Include the following:
 - Xposed Version: `85` 
 - [ ] Xposed Systemless
 - Device OS version: `8.1.0`
 - Device Manufacturer: `XIAO MI`
 - Device Name: `小米 6X`
 - Material Xposed Installer version: `22/08/2018`
 
###### Reproduction Steps

1.  has not module

###### Expected Result
install xposed failed

###### Actual Result

install xposed success

Suggest

support  module form. 

https://dl-xda.xposed.info/framework/

**Comment by DVDAndroid** [comment]
It is not stable, not included in app
