### ISSUE TITLE
DvDandroid Xposed Installer v3.1.5 DL Link?

### ISSUE THREAD

**Issue by ghost** [DVDAndroid/XposedInstaller#206]
I cannot download DvDandroid Xposed Installer latest version inside Xposed Installer
Always parse error my androir os is Marshmallow
![Screenshot_20191119-205813](https://user-images.githubusercontent.com/37603562/69148535-7dba5580-0b0f-11ea-941b-a7d913cded77.png)
![Screenshot_20191119-205820](https://user-images.githubusercontent.com/37603562/69148551-8579fa00-0b0f-11ea-9502-1ac767162b46.png)

**Comment by DVDAndroid** [comment]
Download and install: [this](https://forum.xda-developers.com/devdb/project/dl/?id=31578&task=get)
Check XDA thread if you get errors

**Comment by ghost** [comment]
@DVDAndroid sad I still can't download from the link you are given 😭

**Comment by DVDAndroid** [comment]
[https://androidfilehost.com/?fid=1395089523397969609](https://androidfilehost.com/?fid=1395089523397969609) 

Can't download or corrupt APK?
Can you access to xda link?

**Comment by ghost** [comment]
From the xda link this is what happen
![Screenshot_20191120-070529](https://user-images.githubusercontent.com/37603562/69194551-5c378900-0b64-11ea-9e96-3fb028c7ede1.png)

But I finally downloaded it from data file host link that you give thanks 👍
