### ISSUE TITLE
Module list loading hangs on x86 (and x64) devices

### ISSUE THREAD

**Issue by DVDAndroid** [DVDAndroid/XposedInstaller#35]

**Comment by dgadelha** [comment]
Ouch, it works on ASUS Zenfone 5 (Intel x86).

**Comment by DVDAndroid** [comment]
@dgadelha How many modules you have installed?

**Comment by dgadelha** [comment]
6 modules, no issues at all.

**Comment by DVDAndroid** [comment]
Maybe with more modules, the bug may appear. Can you install other modules (also without enable it) to test this bug?

**Comment by dgadelha** [comment]
How many modules do you want me to install?

**Comment by DVDAndroid** [comment]
I think that 10 modules are sufficient

**Comment by dgadelha** [comment]
It works. Again, no issues at all.

## Screenshots:

[screenshot_20160525-143338](https://cloud.githubusercontent.com/assets/10081640/15550091/2f7e1e26-2286-11e6-8991-788d16244c4a.png)
[screenshot_20160525-143345](https://cloud.githubusercontent.com/assets/10081640/15550095/2fa59df2-2286-11e6-9c1a-c707f351cf62.png)
[screenshot_20160525-143351](https://cloud.githubusercontent.com/assets/10081640/15550093/2fa371c6-2286-11e6-8252-c45ca124dbf7.png)
[screenshot_20160525-143359](https://cloud.githubusercontent.com/assets/10081640/15550096/2fa5f068-2286-11e6-8338-030587888d2a.png)
[screenshot_20160525-143556](https://cloud.githubusercontent.com/assets/10081640/15550094/2fa461d0-2286-11e6-8b84-330461db230d.png)
[screenshot_20160525-143601](https://cloud.githubusercontent.com/assets/10081640/15550097/2fa678da-2286-11e6-9ca2-d959bae228ee.png)

### CPU Info:

[screenshot_20160525-143659](https://cloud.githubusercontent.com/assets/10081640/15550092/2f9a14be-2286-11e6-9168-9d9ca6c1cdaf.png)
[screenshot_20160525-143724](https://cloud.githubusercontent.com/assets/10081640/15550098/2fb79a66-2286-11e6-841c-1cca90312cea.png)

**Comment by DVDAndroid** [comment]
Thanks :+1:
