### ISSUE TITLE
Some images cut off

### ISSUE THREAD

**Issue by terrorist96** [DVDAndroid/XposedInstaller#43]
http://repo.xposed.info/module/com.synergylabs.androidpmp

**Comment by DVDAndroid** [comment]
Sorry, I don't understand

**Comment by terrorist96** [comment]
If you open that module using your installer, some of the screenshot images get cut off; for example the calculator image

**Comment by terrorist96** [comment]
![screenshot_20160209-111028](https://cloud.githubusercontent.com/assets/12802056/12922010/c7c47d68-cf1d-11e5-9aef-ee49f8609737.png)

**Comment by terrorist96** [comment]
Viewing it in landscape mode works fine though.

**Comment by DVDAndroid** [comment]
![screenshot_20160209-172431](https://cloud.githubusercontent.com/assets/6277172/12922548/36bd7a9c-cf52-11e5-9109-f55bc40d7a55.png)

No bugs here. Using Nexus 5 with 445dpi.
Have you changed dpi?

**Comment by terrorist96** [comment]
No, I've never modified my dpi. Nexus 6p. Weird.

**Comment by DVDAndroid** [comment]
![screenshot_20160209-175635](https://cloud.githubusercontent.com/assets/6277172/12923571/8ab001ca-cf56-11e5-8749-059bc9f9c04c.png)

In the description the images are accosted with any new line.
