### ISSUE TITLE
Scroll to bottom in logs

### ISSUE THREAD

**Issue by terrorist96** [DVDAndroid/XposedInstaller#50]
In addition to the scroll to the top button in the logs, I'd like to request a button to do the opposite and scroll down to the end as well.
Thanks. :)

**Comment by terrorist96** [comment]
@DVDAndroid not seeing this in the May 29 update.

**Comment by DVDAndroid** [comment]
No problems here. Maybe the icon moved to 3-dot menu? 

![image](https://cloud.githubusercontent.com/assets/6277172/15642318/d4325f0e-2646-11e6-88dd-fd1e0c3e1e0c.png)

**Comment by terrorist96** [comment]
Ah, I see. I was expecting a downward arrow next to the existing upward arrow, not for it to be buried in the overflow menu.

**Comment by terrorist96** [comment]
@DVDAndroid don't you think it would be better if the scroll to the top and scroll to the bottom buttons were next to each other and displayed in the same manner (instead of displaying one as an icon and the other in the overflow menu button)?

**Comment by DVDAndroid** [comment]
Yes. I'll fix it in next update

**Comment by terrorist96** [comment]
@DVDAndroid small weird thing I'm noticing: if I flick scroll in the logs, then try to click the scroll up/down buttons, it won't work until AFTER the scrolling has stopped. Is this intentional?

**Comment by DVDAndroid** [comment]
It is not intentional but is the normal behavior of the app
