### ISSUE TITLE
[FIXED] Cannot re-enable Xposed after disabling via toggle.

### ISSUE THREAD

**Issue by Chahk** [DVDAndroid/XposedInstaller#63]
If you disable Xposed using the in-app toggle and reboot, the toggle is no longer visible.  You cannot re-enable Xposed via the app, and have to manually delete the `/data/data/de.robv.android.xposed.installer/conf/disabled` file.

**Comment by DVDAndroid** [comment]
Which version of app? 31/05/16?

**Comment by Chahk** [comment]
Yes, 31/05/16 is the version of the app.

**Comment by DVDAndroid** [comment]
Normal or systemless Xposed?

**Comment by Chahk** [comment]
Systemless root and systemless Xposed.

**Comment by DVDAndroid** [comment]
I think that this bug is solved with 22fa2f6d18efd5bd44041f17f320b09232c87189, but before release I'll send you a test apk.

**Comment by DVDAndroid** [comment]
1. Uninstall app
2. Download [this test release](http://www.filedropper.com/xposedinstallerbydvdandroid-debug_3)
3. Reboot and Xposed should be activated by default.
4. Reproduce steps of this bug

**Comment by Chahk** [comment]
The test release fixes the issue!

**Comment by DVDAndroid** [comment]
Nice :+1: 

I'll close this bug when I'll release it
