### ISSUE TITLE
Disabled file 

### ISSUE THREAD

**Issue by edzamber** [DVDAndroid/XposedInstaller#64]
Hi @DVDandroid 

The commit fix disable/enable Toogle is working, but "disabled" file don't disable anything, especially since Xposed Framework v79.

Have a look here...

http://forum.xda-developers.com/showthread.php?p=67126741

**Comment by DVDAndroid** [comment]
See [this](http://forum.xda-developers.com/showpost.php?p=67127932&postcount=775)
