### ISSUE TITLE
Download section not updating modules

### ISSUE THREAD

**Issue by theblixguy** [DVDAndroid/XposedInstaller#65]
The download section doesn't reflect updates made to modules since 31st May (but the updates are reflected on the Xposed Repo website), just wondering if this is a bug in the app or the Xposed Repo?

**Comment by DVDAndroid** [comment]
Xposed Repo. Same issue appeared on 27st May and on original Xposed Installer

![image](https://cloud.githubusercontent.com/assets/6277172/15753492/959fb5e8-28f3-11e6-9bab-c011eee720d9.png)

**Comment by DVDAndroid** [comment]
Seems that now works
